### ISSUE TITLE
``c14n`` as mode does not seem appropriate

### ISSUE THREAD

**Issue by liamdennehy** [w3c-dvcg/http-signatures-test-suite#10]
While ``c14n`` may be used as shorthand for any canonicalisation process, it is very explicitly a function related to XML. This term is also not present anywhere in the specification.

Suggest using ``canonicalize`` exclusively.

**Comment by aljones15** [comment]
I took in your PR:

https://github.com/w3c-dvcg/http-signatures-test-suite/pull/11

and I also changed the Canonicalize tests to use the command: canoncalize
https://github.com/w3c-dvcg/http-signatures-test-suite/commit/947cdc6c4325258f2f9edbd0cec6947abbb255ca

Thank you so much for the input and the PR.
A grep of the test suite shows that c14n has been removed entirely.
